- geti_sdk/http_session/geti_session.py
- geti_sdk/platform_versions.py
- geti_sdk/rest_clients/annotation_clients/annotation_client.py
- geti_sdk/rest_clients/annotation_clients/base_annotation_client.py
- geti_sdk/rest_clients/model_client.py
- geti_sdk/rest_clients/prediction_client.py
- geti_sdk/rest_clients/project_client/project_client.py
- geti_sdk/rest_clients/training_client.py
- geti_sdk/utils/workspace_helpers.py
- tests/integration/http_session/test_geti_session.py
- Remove the dependency on `version.parse`,  which can return a deprecated LegacyVersion object in case the version pattern does not match
- Parse full build version returned by the platform and use that to perform version comparisons
> Update SDK platform version parsing mechanism

- geti_sdk/annotation_readers/base_annotation_reader.py
- geti_sdk/annotation_readers/geti_annotation_reader.py
- geti_sdk/data_models/shapes.py
- geti_sdk/geti.py
If a project is downloaded from an old version of the Geti platform, the annotation files will be in a normalized coordinate system. The newer version of Geti uses a pixel coordinate system. The `GetiAnnotationReader` now auto-detects whether it is reading data for normalized or pixel coordinates, and creates the annotations accordingly.
> Auto detect normalized annotation files for GetiAnnotationReader

- geti_sdk/data_models/status.py
- geti_sdk/rest_clients/model_client.py
- Restore deprecated `project_score` field
- Handle list response in get_all_model_groups endpoint
> Minor changes for backward compatibility with SCv1.1

- geti_sdk/data_models/algorithms.py
- geti_sdk/data_models/annotation_scene.py
- geti_sdk/data_models/annotations.py
- geti_sdk/data_models/configurable_parameter.py
- geti_sdk/data_models/configurable_parameter_group.py
- geti_sdk/data_models/configuration.py
- geti_sdk/data_models/configuration_identifiers.py
- geti_sdk/data_models/job.py
- geti_sdk/data_models/label.py
- geti_sdk/data_models/media.py
- geti_sdk/data_models/media_identifiers.py
- geti_sdk/data_models/model.py
- geti_sdk/data_models/model_group.py
- geti_sdk/data_models/predictions.py
- geti_sdk/data_models/project.py
- geti_sdk/data_models/shapes.py
- geti_sdk/data_models/status.py
- geti_sdk/data_models/task.py
- geti_sdk/data_models/task_annotation_state.py
- geti_sdk/data_models/utils.py
- geti_sdk/deployment/data_models/intermediate_inference_result.py
- geti_sdk/deployment/data_models/region_of_interest.py
- geti_sdk/deployment/deployed_model.py
- geti_sdk/deployment/deployment.py
Previously we were using the legacy attrs API where classes were decorated with `attr.s()` and fields were decorated with `attr.ib()`. Now the classes and fields are decorated with `define()' and `field()`.
> Updated Attrs Classes and Fields

- geti_sdk/data_models/containers/media_list.py
- geti_sdk/rest_clients/annotation_clients/base_annotation_client.py
- geti_sdk/rest_clients/media_client/media_client.py
We make sure that there are no folder separators included in the name. If there are, this would create a nested folder hierarchy that would break uploading of the project
> Validate media filename upon download

- geti_sdk/deployment/deployment.py
- tests/nightly/demos/test_demo_projects.py
- tests/nightly/test_anomaly_classification.py
The `Anomalous` label was not recognized as such correctly in the deployment for anomaly models. This PR introduces a workaround that fixes that, upon loading the inference models for anomaly type tasks.
> Fix anomaly classification deployment

- README.md
- examples/README.md
- examples/create_coco_project_single_task.py
- examples/create_coco_project_task_chain.py
- examples/create_demo_projects.py
- examples/upload_and_predict_from_numpy.py
- examples/upload_and_predict_media_from_folder.py
- geti_sdk/geti.py
- geti_sdk/http_session/geti_session.py
- geti_sdk/http_session/server_config.py
- geti_sdk/utils/credentials_helpers.py
- notebooks/001_create_project.ipynb
- notebooks/002_create_project_from_dataset.ipynb
- notebooks/003_upload_and_predict_image.ipynb
- notebooks/004_create_pipeline_project_from_dataset.ipynb
- notebooks/005_modify_image.ipynb
- notebooks/006_reconfigure_task.ipynb
- notebooks/007_train_project.ipynb
- notebooks/008_deploy_project.ipynb
- notebooks/009_download_and_upload_project.ipynb
- notebooks/README.md
- notebooks/use_cases/101_simulate_low_light_product_inspection.ipynb
- tests/conftest.py
- tests/fixtures/geti.py
- tests/integration/utils/test_utils.py
This PR enables SSL certificate validation in the `Geti` class by default. It can still be disabled by passing `verify_certificate=False` to the Geti constructor.
> Enable SSL certificate validation by default

- geti_sdk/data_models/annotation_scene.py
- geti_sdk/data_models/annotations.py
- geti_sdk/data_models/label.py
- geti_sdk/data_models/shapes.py
- geti_sdk/utils/plot_helpers.py
- tests/fixtures/unit_tests/annotation.py
- tests/fixtures/unit_tests/dates.py
- tests/fixtures/unit_tests/media.py
- tests/pre-merge/unit/rest_converters/test_normalized_annotation_rest_converter_unit.py
- tests/pre-merge/unit/utils/test_plot_helpers_unit.py
1. Enable the use of the OTE SDK `Visualizer` class to show annotations and predictions in images/videos, following the style of the Geti UI
2. Add unit tests for the `plot_helpers` module
> Use OTE SDK visualizer, add plot helper unit tests

- geti_sdk/utils/credentials_helpers.py
- tests/data/mock.env
- tests/pre-merge/integration/utils/test_utils.py
This PR enables specifying a proxy for https communication in the `.env` file, to allow easy configuration of proxy settings.
> Add HTTPS_PROXY as variable to the credentials helper

- geti_sdk/utils/plot_helpers.py
- tests/pre-merge/unit/utils/test_plot_helpers_unit.py
Add a `cv2.waitKey()` step after closing the window to prevent the process from stalling.
> Fix opencv window closure bug

- geti_sdk/deployment/deployed_model.py
- geti_sdk/deployment/deployment.py
- geti_sdk/rest_clients/deployment_client.py
This PR moves the responsibility for cleaning up temporary resource from the `DeploymentClient` to the `Deployment` itself. This fixes an issue that could cause the resources to be removed prematurely.
> Fix issue with temporary resource clean up for `Deployment`s

- examples/upload_and_predict_from_numpy.py
- geti_sdk/data_models/media.py
- geti_sdk/http_session/geti_session.py
- geti_sdk/utils/plot_helpers.py
- notebooks/001_create_project.ipynb
- notebooks/002_create_project_from_dataset.ipynb
- notebooks/003_upload_and_predict_image.ipynb
- notebooks/005_modify_image.ipynb
- notebooks/008_deploy_project.ipynb
- tests/pre-merge/unit/utils/test_plot_helpers_unit.py
`show_image_with_annotation_scene` now uses PIL to display images, instead of openCV.
This PR also adds a `channel_order` input parameter that accepts either `rgb` (default) or `bgr`. It should be set to reflect the channel order of the input image.
> Cvs-96625 Update image display method in `show_image_with_annotation_scene`

- geti_sdk/deployment/deployed_model.py
- geti_sdk/deployment/deployment.py
- notebooks/008_deploy_project.ipynb
Saving `deployments` works again, and it is no longer possible to save a deployment to the same target folder twice. Previously this would lead to data corruption, now this will result in a failed `deployment.save` operation while preserving the deployment in the target location.
> Fix deployment saving mechanism and handle errors

- tests/helpers/project_helpers.py
- tests/helpers/project_service.py
- tests/nightly/test_nightly_project.py
To make sure auto-training is started after project creation and media upload, the annotation requirements are set to 6 instead of 12 for the nightly tests.
> Fix nightly tests for classification project

- geti_sdk/data_models/predictions.py
- geti_sdk/deployment/deployed_model.py
- geti_sdk/deployment/deployment.py
- tests/nightly/test_nightly_project.py
- tests/pre-merge/integration/test_geti.py
The method `Deployment.explain()` performs inference and returns a Prediction with a saliency map and feature vector for the input image. When `explain` is used for a task-chain deployment, the saliency map and feature vector are generated only for the first task in the chain.
> Add `explain` method for deployment

- geti_sdk/data_models/status.py
The `project_performance.score` of the project in training comes in as NoneType. To avoid the `unsupported operand type(s) for *: 'NoneType' and 'int'` that occurs in this case, added an if statement to check for NoneType.
Related Issue: https://jira.devtools.intel.com/browse/CVS-108934
> Add score NoneType check in summary function of ProjectStatus

- .pre-commit-config.yaml
This is the fix for the issue #234
> upgrate isort to 5.12.0 to avoid runtime error in pre-commit in python 3.8

- geti_sdk/data_models/project.py
Modify to support new project REST API (Geti-1.8.0-on_prem) keys
Related Issue: https://jira.devtools.intel.com/browse/CVS-116394
```
export interface ProjectDTO extends ProjectCommon {
creation_time: string;
id: string;
name: string;
datasets: DatasetDTO[];
pipeline: {
connections: ConnectionDTO[];
tasks: TaskDTO[];
};
performance: PerformanceDTO;
thumbnail: string;
storage_info?: { size: number } | Record<string, never>;  # New added in Geti-1.8.0
}
```
> Fix for responding to Project Key values in the REST API

- geti_sdk/data_models/job.py
- geti_sdk/rest_clients/training_client.py
- geti_sdk/utils/job_helpers.py
- notebooks/007_train_project.ipynb
This PR updates the `TrainingClient().monitor_jobs` function to use progress bars, instead of periodic log output. 
It also adds a `monitor_job` method to the traning client, for monitoring a single job. The functionality is the same as `monitor_jobs`, which can be used for a list of jobs.
> Change job monitor functions to use progress bars

- .gitignore
- geti_sdk/benchmarking/__init__.py
- geti_sdk/benchmarking/benchmarker.py
- geti_sdk/benchmarking/utils.py
- geti_sdk/data_models/model.py
- geti_sdk/rest_clients/deployment_client.py
- geti_sdk/rest_clients/model_client.py
- notebooks/011_benchmarking_models.ipynb
- requirements/requirements-notebooks.txt
The `Benchmarker` class is a tool for setting up and managing benchmarks of Geti models on local hardware. At the moment, only benchmarking of the inference rate for the local deployments is supported, but accuracy benchmarking may be added in the future. Currently, the `Benchmarker` allows the user to do the following:
- Specify a project for which models should be benchmarked (can be either single task or task-chain)
- Specify which model architectures should be included 
- Specify which precision levels should be used (i.e. FP16, INT8, ...)
- Specify the media on which the benchmark should run (images from Geti or local images, or a video)
Once this has been specified, the `Benchmarker` will prepare the project. This means it will check whether all required models and optimized models …
> Add `Benchmarker` class and demo notebook for inference throughput benchmarking of Geti models

- tests/fixtures/unit_tests/benchmarker.py
- tests/fixtures/unit_tests/project.py
- tests/nightly/test_classification.py
- tests/nightly/test_detection_to_classification.py
- tests/pre-merge/unit/benchmarking/test_benchmarker.py
This PR introduces unit tests and nightly integration tests for the Benchmarking package.
> Test benchmarker

- geti_sdk/deployment/deployment.py
- geti_sdk/rest_clients/deployment_client.py
This PR fixes two bugs:
1. Add a timeout to deployment creation, so that it no longer stalls infinitely if the progress on the Geti server fails silently or gets stuck somehow.
2. Handle Path objects in the `Deployment.from_folder` method
> Minor bug fixes related to deployment

- geti_sdk/data_models/job.py
This PR updates the `ModelMetadata` data model, to account for changes in Geti v1.14
> Add `model_activated` field to ModelMetadata

- geti_sdk/data_models/annotation_scene.py
- geti_sdk/data_models/predictions.py
- geti_sdk/rest_clients/prediction_client.py
This PR fixes an issue with the label color for predictions generated by the `PredictionClient.predict_image` method. Colors and names for the predicted labels should now be set correctly.
> Fix issue with undefined label color for prediction

- README.md
Unfortunately the geti-sdk is not yet compatible with python v3.10 on macOS. The compatibility table in the README.md was updated to reflect this.
> Update compatibility table in README

- geti_sdk/deployment/deployed_model.py
- geti_sdk/deployment/deployment.py
- geti_sdk/deployment/legacy_converters/__init__.py
- geti_sdk/deployment/legacy_converters/legacy_anomaly_converter.py
- requirements/requirements.txt
In Geti v1.13 and up, the prediction output of the anomaly models has changed. To handle the new output properly, `otx==1.4.4` is required. Therefore, this PR:
1. Updates the `otx` requirement to `otx==1.4.4`
2. Adds a legacy anomaly prediction conversion mechanism, for models created with Geti v1.8 and below
3. Slightly modifies the `deployment.save` mechanism to be compatible with the new conversion structure in Geti v1.13 and up
As a result, the SDK is now compatible with model deployment for both Geti v1.8 and Geti v1.14 for all tasks and models.
> Add compatibility for anomaly model deployment for Geti v1.13 and up

- geti_sdk/http_session/geti_session.py
This PR fixed geti_session.get_rest_response method calls
> geti_session - remove unused proxy kwargs

- geti_sdk/http_session/geti_session.py
There has been an update to the endpoint to retrieve the organization ID for a given personal access token. This PR accounts for that.
> Fix organization retrieval URL with PAT

- .github/workflows/record-vcr-cassettes.yaml
This PR introduces a manual GItHub action workflow that rebuilds VCR cassettes and pushes it back to the branch
> TEST: add VCR recording workflow

- geti_sdk/rest_clients/model_client.py
This PR updates the `optimize_model` method to account for changes in how the job id is returned from the server.
> Fix job id retrieval in optimize_model method

- geti_sdk/data_models/job.py
- geti_sdk/data_models/status.py
- geti_sdk/demos/demo_projects/utils.py
- geti_sdk/rest_clients/model_client.py
- geti_sdk/rest_clients/training_client.py
- geti_sdk/utils/job_helpers.py
- tests/nightly/test_nightly_project.py
- tests/pre-merge/integration/rest_clients/test_model_and_prediction_client.py
- tests/pre-merge/integration/rest_clients/test_training_client.py
This PR makes `Job.description` and `Job.status` optional, to account for changes in the REST contract for jobs in Geti v1.16
> Update job datamodel

- tests/pre-merge/integration/rest_clients/test_annotation_client.py
Attempt to fix an issue that sometimes causes the integration tests to fail in ONLINE or RECORD mode. Add a short delay between annotation upload and annotation retrieval, to make sure the server has enough time to process the uploaded annotations
> Add short delay in annotation client video tests

- .github/workflows/record-vcr-cassettes.yaml
This PR adds an option to start the cassettes recording workflow form a `/record` comment in PR
> Record VCR cassettes by a comment in PR

- .github/workflows/pre-merge-tests.yml
- .github/workflows/security-scan.yaml
To ensure compliance with OpenSSF requirements, this PR further restricts the permissions for the github actions workflows. They should still have sufficient permissions to function normally.
> Further restrict workflow permissions

- geti_sdk/data_models/media.py
This PR updates the data model for `Video` media items, to account for changes in the Geti REST API
> Update `Video` data model with annotation statistics

- geti_sdk/rest_clients/model_client.py
This simplifies the interaction with Model objects later on, because it establishes a link to the parent ModelGroup.
> Add `model_storage_id` to models when fetching model group

- geti_sdk/data_models/algorithms.py
- geti_sdk/data_models/job.py
- geti_sdk/data_models/label.py
- geti_sdk/data_models/media.py
- geti_sdk/data_models/model.py
- geti_sdk/data_models/performance.py
- geti_sdk/data_models/status.py
- geti_sdk/deployment/deployed_model.py
- geti_sdk/http_session/geti_session.py
- geti_sdk/rest_clients/annotation_clients/base_annotation_client.py
- geti_sdk/rest_clients/dataset_client.py
- geti_sdk/rest_clients/deployment_client.py
- geti_sdk/rest_clients/media_client/media_client.py
- geti_sdk/rest_clients/model_client.py
- geti_sdk/rest_clients/prediction_client.py
- geti_sdk/rest_clients/training_client.py
- geti_sdk/utils/algorithm_helpers.py
- tests/fixtures/unit_tests/geti.py
- tests/pre-merge/integration/http_session/test_geti_session.py
- tests/pre-merge/unit/http_session/test_geti_session_unit.py
- tests/pre-merge/unit/test_geti_unit.py
This PR drops support for older GETi Platform versions (1.8 and older).  It ends support for all interactions with older Platforms, including logging in.
It opens several paths for users:
1. Users can upgrade their platform to 2.0 and use the GETi-SDK 2.0 package with it.
2. Users who decide to stay with an older Platform version can use a corresponding GETi-SDK package.
3. Users with complex pipelines, including model deployments by both legacy and contemporary versions of the Platform, should use separate virtual environments.
SaaS users should not be affected by these changes.
> End support for Platforms versions lower than 1.15

- geti_sdk/data_models/media.py
- geti_sdk/rest_clients/media_client/video_client.py
Some time ago we removed the tempfile handling for video's that were uploaded from numpy arrays. However, this gave issues in one of the example scripts, which would fail because it couldn't access the video data. This PR reinstates the tempfiles in this case, and adds additional exit handling to make sure the tempfile gets deleted eventually.
> Undo changes to video tempfile handling, register atexit handler for tempfile deletion

- geti_sdk/data_models/annotation_scene.py
- geti_sdk/data_models/utils.py
- geti_sdk/deployment/deployed_model.py
- geti_sdk/deployment/predictions_postprocessing/results_converter/results_to_prediction_converter.py
- geti_sdk/prediction_visualization/visualizer.py
This PR introduces means to extract saliency maps from predictions and prepare overlays for visualization
> Saliency map visualization

- geti_sdk/data_models/containers/algorithm_list.py
- geti_sdk/data_models/model.py
- notebooks/013_manage_models.ipynb
This PR introduces a new example notebook showcasing work with models and algorithms
> Add a model management notebook

- .github/workflows/nightly-tests-geti-develop.yaml
- .github/workflows/nightly-tests-geti-latest.yaml
- .github/workflows/nightly-tests-geti-mvp.yaml
- .github/workflows/nightly-tests.yaml
This PR fixes the conda environment activation in the nightly tests after transitioning from `miniconda` to `miniforge`
> Update nightly test conda env directory

- geti_sdk/platform_versions.py
- tests/pre-merge/integration/http_session/test_geti_session.py
- tests/pre-merge/unit/test_platform_version_unit.py
The SaaS returns a strange build time tag that breaks the version validation.
> Fix `is_geti` version check

- .github/workflows/build-package-internal-pypi.yaml
- .github/workflows/build-package-pypi.yaml
- .github/workflows/build-package-test-pypi.yaml
- .github/workflows/build-package.yaml
The workflow for publishing a release to the intel-internal pypi needs to run on the self-hosted runner, otherwise it cannot reach the internal pypi server.
> Fix build and publish workflow for internal pypi

- geti_sdk/platform_versions.py
- tests/pre-merge/integration/http_session/test_geti_session.py
- tests/pre-merge/unit/test_platform_version_unit.py
* Fix `is_geti` version check
The SaaS returns a strange build time tag that breaks the version validation.
* Update test_platform_version_unit.py
* Update test_geti_session.py
* Update test_platform_version_unit.py
* Update test_platform_version_unit.py
> Fix `is_geti` version check (#434)

- docs/source/geti_sdk.import_export.rst
The page that `api_reference.rst` is pointing to is missing currently
> Create geti_sdk.import_export docs page

- geti_sdk/demos/data_helpers/anomaly_helpers.py
There is a self-signed certificate in the chain for the target url. This would cause the certificate validation (and hence the download) to fail in some cases.
We still validate the hash of the downloaded file, so not validating the certificate does not introduce a security risk. Also there is no sensitive (user) information exchanged when downloading the file.
> Disable certificate validation for mvtec dataset download

- .github/workflows/build-wheels.yaml
- pyproject.toml
- setup.py
At the moment, installing the geti-sdk on macOS, or on any machine with arm64 architecture will require building datumaro from source. This requires Rust to be installed, which not all of our users may have. This PR is a first step to address this by building wheels for these OS'es and architectures, using the `cibuildwheels` library. It is still experimental, most likely the configuration needs to be tweaked for it to work.
Once building the wheels works, the next step would be to add a job that pulls the artifacts and publishes them to pypi.
> Create workflow to build wheels for different OS/CPU architecture combinations

- geti_sdk/data_models/model.py
This new field reflects the integral size of the model and all the accompanying files, it is the size that will be freed if the model is purged.
> Update the Model schema to include the `total_disk_size` field 

- geti_sdk/__init__.py
- geti_sdk/_version.py
- geti_sdk/geti.py
- geti_sdk/http_session/geti_session.py
- setup.py
- tests/fixtures/unit_tests/geti.py
- tests/pre-merge/unit/http_session/test_geti_session_unit.py
- tests/pre-merge/unit/test_geti_unit.py
SaaS users may experience silent platform updates, thus they need to be reminded to upgrade the SDK package.
> Implement Platform version check

- geti_sdk/rest_clients/credit_system_client.py
The servers with the Credit System disabled return an empty 200 response when called with a cookie and an HTML page when called with an API token.
This PR adds support for both cases.
> Allow Credit System-less servers authenticate with a token

- geti_sdk/rest_clients/annotation_clients/base_annotation_client.py
Annotation reader now includes all the label names (both from the on-disk source and remote project) in the label_name to id mapping
> Fix annotation reader

- examples/upload_and_predict_from_numpy.py
- examples/upload_and_predict_media_from_folder.py
- geti_sdk/benchmarking/benchmarker.py
- geti_sdk/geti.py
- geti_sdk/import_export/import_export_module.py
- geti_sdk/import_export/tus_uploader.py
- geti_sdk/rest_clients/project_client/project_client.py
- notebooks/001_create_project.ipynb
- notebooks/003_upload_and_predict_image.ipynb
- notebooks/005_modify_image.ipynb
- notebooks/006_reconfigure_task.ipynb
- notebooks/007_train_project.ipynb
- notebooks/011_benchmarking_models.ipynb
- notebooks/014_asynchronous_inference.ipynb
- tests/fixtures/demos.py
- tests/fixtures/projects.py
- tests/fixtures/unit_tests/benchmarker.py
- tests/helpers/finalizers.py
- tests/helpers/project_helpers.py
- tests/helpers/project_service.py
- tests/nightly/demos/test_demo_projects.py
- tests/nightly/test_anomaly_classification.py
- tests/nightly/test_classification.py
- tests/nightly/test_nightly_project.py
- tests/pre-merge/integration/test_geti.py
- tests/pre-merge/unit/benchmarking/test_benchmarker.py
- tests/pre-merge/unit/test_geti_unit.py
This PR adds guardrails to the user workflow that should streamline the experience of working with identically named projects.
The `get_project` now may be called with one of [project_name, project_id, project_object].
Fetching a project by name now has an unraveled logic scheme and is THE place where the user can determine the correct `project_id`.
All the other methods now accept a project object as an argument instead of a project_name which may be potentially problematic.
> Project access refactoring

- geti_sdk/deployment/deployment.py
- geti_sdk/rest_converters/project_rest_converter.py
This fixes an issue in which the label ID <-> name matching failed for deployments that were saved to disk
> Keep label ID's intact on saving project deployment

- examples/README.md
- geti_sdk/geti.py
- notebooks/012_post_inference_hooks.ipynb
- notebooks/014_asynchronous_inference.ipynb
- tests/nightly/test_nightly_project.py
- tests/pre-merge/integration/test_geti.py
Fixes: CVS-156929
Notebooks and examples show that you can deploy projects by their name but this was not implemented. Notebooks 12 and 14 would not run successful because of this.
This PR fixes that by requiring either the project object or the project name in the Geti.deploy_project() method.
> Project deployment by name

- examples/README.md
- geti_sdk/demos/demo_projects/coco_demos.py
- geti_sdk/demos/demo_projects/utils.py
- geti_sdk/geti.py
- notebooks/001_create_project.ipynb
- notebooks/003_upload_and_predict_image.ipynb
- notebooks/004_create_pipeline_project_from_dataset.ipynb
- notebooks/006_reconfigure_task.ipynb
- notebooks/007_train_project.ipynb
- notebooks/008_deploy_project.ipynb
- notebooks/009_download_and_upload_project.ipynb
- notebooks/010_model_serving.ipynb
- notebooks/011_benchmarking_models.ipynb
- notebooks/012_post_inference_hooks.ipynb
- notebooks/013_manage_models.ipynb
- notebooks/014_asynchronous_inference.ipynb
- notebooks/use_cases/101_simulate_low_light_product_inspection.ipynb
- tests/nightly/test_nightly_project.py
- tests/pre-merge/integration/test_geti.py
Changes in this PR:
- Project deployment by name raised error as it expected project object. Fixes several notebooks
- Wait for job to appear in job queue before checking job status.
- Project deletion after creation in notebook would raise error because job creation kafka event was not yet done. Commented out the delete operation in the cell so E2E tests can test the notebook
> Fix errors in notebooks when running from E2E tests

- tests/fixtures/vcr_config.py
The function would raise an error (`None` has no method `replace`) when you configure only one proxy, e.g. `https_proxy` but not `http_proxy`.
> Fix VCR config for unset proxy

- geti_sdk/utils/serialization_helpers.py
- tests/pre-merge/unit/utils/test_utils_unit.py
Changes:
- Improve HTTP response parser to tolerate extra keys
- the extra keys often originate from non-breaking API changes and mismatching SDK versions
> Tolerate extra keys when deserializing HTTP response [2.6.0]

- geti_sdk/utils/serialization_helpers.py
- tests/pre-merge/unit/utils/test_utils_unit.py
Changes:
- Improve HTTP response parser to tolerate extra keys
- the extra keys often originate from non-breaking API changes and mismatching SDK versions
> Tolerate extra keys when deserializing HTTP response

- geti_sdk/deployment/predictions_postprocessing/results_converter/results_to_prediction_converter.py
Filter out empty label ID in Model's configuration.
Release 2.6 PR: https://github.com/openvinotoolkit/geti-sdk/pull/535
> CVS-159908 - Fix empty label ID in configuration [develop]

- geti_sdk/data_models/algorithms.py
- geti_sdk/data_models/configurable_parameter.py
- geti_sdk/data_models/configurable_parameter_group.py
- geti_sdk/data_models/configuration.py
- geti_sdk/rest_clients/training_client.py
[CVS-160100](https://jira.devtools.intel.com/browse/CVS-160100)
HPO will be deprecated in Geti 2.7, impact on the REST API:
Deprecated parameters:
- `supports_auto_hpo` from the supported algorithm endpoint response
- `enable_hyper_parameter_optimization` and `hpo_parameters` from training endpoint request
Removed parameters:
- `auto_hpo_state` and `auto_hpo_value` are removed from project configuration endpoint response
> CVS-160100 - Deprecate HPO

- .github/workflows/build-docs.yaml
- .github/workflows/build-package.yaml
- .github/workflows/build-wheels.yaml
- .github/workflows/pre-merge-tests.yml
- .github/workflows/scorecard.yml
- .github/workflows/security-scan.yaml
- .readthedocs.yaml
- README.md
- geti_sdk/data_models/configurable_parameter_group.py
- geti_sdk/data_models/utils.py
- geti_sdk/demos/data_helpers/video_helpers.py
- geti_sdk/rest_clients/prediction_client.py
- geti_sdk/rest_converters/configuration_rest_converter.py
- setup.py
- tests/conftest.py
- tests/fixtures/geti.py
- tests/fixtures/vcr_config.py
- tests/pre-merge/unit/deployment/test_prediction_converter.py
This PR updates the CI with Python 3.12 support.
I have also fixed a bug whereby saliency images where saved as base64 instead of raw jpg.
I have also bump the version of upload-artifact as v3 is deprecated and does not work anymore.
> Add support for Python 3.12 and update CI Ubuntu version

- notebooks/010_model_serving.ipynb
`Visualizer` expects a RGB image as input
> bugfix: swapped color channels when visualizing prediction sample (notebook 10)

- geti_sdk/geti.py
- geti_sdk/rest_clients/credit_system_client.py
- geti_sdk/utils/__init__.py
- geti_sdk/utils/workspace_helpers.py
- tests/fixtures/unit_tests/geti.py
- tests/pre-merge/unit/test_geti_unit.py
If there is only one workspace, that is selected; if there are 2+, then an error is raised requesting the user to provide an explicit workspace_id.
> Improve automatic workspace selection

- geti_sdk/geti.py
- geti_sdk/rest_clients/credit_system_client.py
- geti_sdk/utils/__init__.py
- geti_sdk/utils/workspace_helpers.py
- tests/fixtures/unit_tests/geti.py
- tests/pre-merge/unit/test_geti_unit.py
This PR fixes an issue with the automatic selection of the workspace. The previous logic, based on hardcoded names, is replaced by a more reliable algorithm: if there is only one workspace to choose from, that is automatically selected; if there are 2+, then the user must pick one explicitly (through the `workspace_id` parameter) otherwise the SDK throws an error.
> Improve automatic workspace selection [2.7]

- geti_sdk/deployment/deployed_model.py
- geti_sdk/deployment/predictions_postprocessing/results_converter/results_to_prediction_converter.py
- requirements/requirements.txt
- tests/pre-merge/unit/deployment/test_prediction_converter.py
[CVS-162946](https://jira.devtools.intel.com/browse/CVS-162946)
- Implement new label management for prediction converters (implementation is now similar to how Geti manages labels).
- Introduce improvements for converting semantic segmentation results (requires `openvino-model-api==0.2.5.1`)
Manually tested inference with all supported task types.
> CVS-162946 - Fix inference converters

- geti_sdk/deployment/predictions_postprocessing/results_converter/results_to_prediction_converter.py
- tests/pre-merge/unit/deployment/test_prediction_converter.py
Fix bug: If a project has label names like 1, the model returns labels as list[int] instead of list[str], which the converter class does not expect.
> CVS-163037 - Fix inference converter

- .github/workflows/bandit.yaml
- .github/workflows/build-docs.yaml
- .github/workflows/build-wheels.yaml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yaml
- .github/workflows/pre-merge-tests.yml
- .github/workflows/scorecard.yml
- .github/workflows/security-scan.yaml
- .github/workflows/zizmor-scan.yaml
- .github/zizmor.yaml
This PR introduces [zizmor](https://github.com/woodruffw/zizmor) linter for GitHub actions workflows to prevent and detect potential issues in workflows:
- check PR into workflows, fail only if high severity issues is detected
- periodic scan (all severity), generates SARIF output and upload it into GitHub Security tab for future analysis
- false positives with justification can be added into `.github\zizmor.yaml`
Also, minor issues flagged by zizmor in the current workflows are fixed in this PR.
> Use zizmor linter to check workflows

- requirements/requirements-dev.txt
Corrected the `pytest-recording` version to 0.13.2 due to issues with `os.pathconf` not being present on Windows systems.
This error is caused by a regression in that package in 0.13.3: https://github.com/kiwicom/pytest-recording/issues/174
GHA
```python
#
#
#
```
> Correct pytest-recording version

- CHANGELOG.md
- geti_sdk/rest_clients/project_client/project_client.py
It is now possible to update the colors/hotkeys of the project labels via SDK.
Relates to #597
Example:
```python
project = project_client.update_labels(
project=project,
colors_to_update={"a": "#ff0000", "b": "#00ff00"},
hotkeys_to_update={"b": "SHIFT+N", "c": "SHIFT+M"},
)
```
```python
#
#
#
```
> ProjectClient: add method to update label colors/hotkeys [2.10]

- geti_sdk/benchmarking/benchmarker.py
- geti_sdk/rest_clients/model_client.py
- tests/pre-merge/unit/benchmarking/test_benchmarker.py
Send empty payload to optimize endpoint, since there is only one possible optimize method left, POT. Also deprecated optimization type input parameter.
Optimize endpoint already accepts empty payload and NNCF support was removed already.
> ITEP-33055: Send empty payload to optimize endpoint

- geti_sdk/deployment/deployed_model.py
- geti_sdk/deployment/predictions_postprocessing/results_converter/results_to_prediction_converter.py
1.  Fixes an issue where labels were being converted from strings to floats (e.g., "label name" -> `LabelName`, `"1"` -> `1.0`). Label names should be treated as strings, not converted numerically.
2.  Prevents label renaming issues after training. If a model is trained with specific label names, e.g., `["1", "2", "3"]`, and those labels are later renamed (e.g., to `["one", "2", "3"]`), infer the correct label by the XML configuration "label_ids". 
```python
#
#
#
```
> ITEP-70998- Bugfix: inference for keypoint detection crashes

- geti_sdk/annotation_readers/datumaro_annotation_reader/datumaro_annotation_reader.py
- geti_sdk/annotation_readers/datumaro_annotation_reader/datumaro_dataset.py
- geti_sdk/utils/__init__.py
- geti_sdk/utils/deprecation.py
Deprecate old Datumaro classes. These classes were introduced before the native Geti Dataset Improt/Export functionality was supported. The recommended way of importing annotations/datasets has been through Geti Dataset import/export instead for a long time now. We deprecate these classes, because they make Geti SDK depend on datumaro, which is a pretty heavy dependency. In the future we will remove these classes and their dependencies from the Geti SDK.
Everything should work as before, except a FutureWarning should be raised whenever someone initializes a DatumaroAnnotationReader or Dataset class.
```python
#
#
#
```
> ITEP-70633: Deprecate Datumaro classes

- geti_sdk/import_export/import_export_module.py
Fix a bug where `GetiIE.import_project` would sometimes fail to retrieve the project right after importing it. This is caused by eventual consistency in the Geti job metadata; after waiting for a few second, the method now refreshes the job metadata to find the project id.
> bugfix: cannot find project after import

- geti_sdk/data_models/enums/include_models.py
- geti_sdk/geti.py
- geti_sdk/import_export/import_export_module.py
Support the include_models query parameter for project export. This allows the user to specify which models to export, with the options to include all, none or only the latest active model.
```python
#
#
#
```
> Support include_models query parameter in export project

- .github/workflows/pre-merge-tests.yml
- README.md
- pyproject.toml
- uv.lock
Dropping support for python 3.9: this Python version is very old and almost reached its EOL. Users should update to a newer Python version.
> drop support for Python 3.9

- geti_sdk/rest_clients/model_client.py
In projects that have visual prompting models, the method `ModelClient.get_all_model_groups` would fail when trying to retrieve the (non-existing) manifests of these models.
> bugfix: `ModelClient.get_all_model_groups` would fail with visual prompting models

- .github/workflows/build-package-pypi.yaml
- .github/workflows/build-package-test-pypi.yaml
- .github/workflows/pre-merge-tests.yml
- .github/workflows/security-scan.yaml
- CONTRIBUTING.md
This PR adds a Semgrep scan in the CI (`push` trigger). Checks on the `pull_request` trigger will be enabled in a separate PR.
In addition:
- Updated contribution guidelines with application security-related information
- Fixed several Zizmor findings
```python
#
#
#
```
> feat(ci): adding Semgrep in the CI
