requirements/requirements-notebooks.txt
requirements/requirements.txt

Update required versions of various packages

Update numpy, ipython, jupyterlab versions

---

geti_sdk/geti.py
geti_sdk/utils/project_helpers.py
requirements/requirements.txt

This PR makes sure that the target folder chosen for downloading a project is a valid path name

Add path validation to project download target path

---

geti_sdk/demos/data_helpers/anomaly_helpers.py
geti_sdk/demos/data_helpers/coco_helpers.py
geti_sdk/demos/data_helpers/download_helpers.py
geti_sdk/deployment/deployed_model.py
geti_sdk/deployment/deployment.py
geti_sdk/geti.py
geti_sdk/rest_clients/annotation_clients/base_annotation_client.py
geti_sdk/rest_clients/configuration_client.py
geti_sdk/rest_clients/media_client/media_client.py
geti_sdk/rest_clients/model_client.py
geti_sdk/rest_clients/prediction_client.py
geti_sdk/rest_clients/project_client/project_client.py

This PR restricts the permissions for all calls to `os.makedirs`

Reduce permissions upon directory creation

---

geti_sdk/data_models/job.py

Keeping job datamodel up to date with geti-develop

Add `ScoreMetadata` to represent the new `scores` field

---

geti_sdk/data_models/model.py

Disable slots on `BaseModel` class

Fix issue with model to dictionary conversion

---

geti_sdk/demos/__init__.py
geti_sdk/demos/data_helpers/__init__.py
geti_sdk/demos/data_helpers/anomaly_helpers.py
geti_sdk/demos/data_helpers/download_helpers.py
geti_sdk/deployment/deployed_model.py
geti_sdk/deployment/deployment.py
geti_sdk/deployment/resources/OVMS_README.md
geti_sdk/deployment/resources/__init__.py
geti_sdk/deployment/resources/requirements-ovms.txt
geti_sdk/deployment/utils.py
geti_sdk/geti.py
geti_sdk/rest_clients/deployment_client.py
geti_sdk/rest_clients/project_client/project_client.py
notebooks/004_create_pipeline_project_from_dataset.ipynb
notebooks/010_model_serving.ipynb

This PR enables project-level deployment via OVMS

Enable OVMS deployment

---

examples/upload_and_predict_from_numpy.py

Save the result image to file after predicting

Fix `upload_and_predict_from_numpy.py` example

---

geti_sdk/deployment/deployment.py

Added tuple as accepted return type for model inference

Fix deployment postprocessing

---

geti_sdk/data_models/model.py
geti_sdk/rest_clients/model_client.py

This PR adds methods that help in the process of selecting an optimized model, for example when preparing a deployment.
In particular, it adds `ModelClient.get_latest_optimized_model`, which fetches the most recently created optimized model for a certain algorithm, precision and optimization type.

Improve model selection mechanism

---

MANIFEST.in
geti_sdk/utils/algorithm_helpers.py
geti_sdk/utils/legacy_algorithms.json

This PR adds a workaround to be able to use the deprecated supported algorithms endpoint in recent Geti versions.

Supported algorithms workaround

---

tests/README.md

This PR adds a NOTE section in test/README.md describing how to download the VCR data.

Mention git lfs in test docs

---

.github/workflows/security-scan.yaml

Snyk has been deprecated and access to the API has been revoked. Removing it from the workflow

Remove snyk scan from security workflow

---

.gitignore
README.md

Add badges for:
- Version compatibility: python, openvino, Intel Geti version
- Test status: pre-merge, nightly [geti latest], nightly [geti develop]
- OpenSSF scorecard passing badge

Add shields.io badges to readme

---

geti_sdk/data_models/job.py
geti_sdk/http_session/geti_session.py
geti_sdk/rest_clients/training_client.py
geti_sdk/utils/job_helpers.py
tests/nightly/test_nightly_project.py

This PR adds handling for 403 Forbidden errors when monitoring job status, and streamlines retrieving the current job step name.

Improve robustness of job monitoring

---

geti_sdk/deployment/deployment.py

Minor fix in the deployment for maskrcnn based models

Fix maskrcnn postprocessing for geti v1.15

---

.github/workflows/scorecard.yml

Add openssf scorecard code scanning

---

geti_sdk/rest_clients/media_client/media_client.py
geti_sdk/rest_clients/media_client/video_client.py

Remove temp file after calling `upload_video()` with a numpy array.
CVS-137878

Сlean up temp file for video numpy array

---

.github/workflows/pre-merge-tests.yml
requirements/requirements.txt
setup.py

Updates:
- `setup.py`
- `requirements.txt` (bumps up openvino and datmaro)
- Updates pre-commit workflow

Add Python 3.11 support; Deprecate Python 3.8

---

geti_sdk/data_models/model.py
geti_sdk/data_models/model_group.py

Introduce data_model `purge_info` field

---

notebooks/008_deploy_project.ipynb

The `release` version of PR #454

Use proper project name in notebook 008

---

notebooks/005_modify_image.ipynb

This PR fixes an issue in 005 example notebook

Fix 005_modify_image.ipynb image usage

---

geti_sdk/rest_clients/project_client/project_client.py

This PR fixes the confirmation procedure for `ProjectClient.delete_project` method

Fix `delete_project` method

---

geti_sdk/geti.py

Replace Project ID assertion with explicit value check

---

geti_sdk/rest_clients/annotation_clients/base_annotation_client.py

148583
This PR solves "No object" -> "No Object" detection empty label mapping

Perform case-insensitive label mapping while reading labels from a folder

---

README.md

Remove mention of Anaconda from README

---

geti_sdk/rest_clients/project_client/task_templates.py

This PR brings a small fix to the anomaly reduction transformation for a bug that prevents deployment

Fix anomaly task title

---

geti_sdk/deployment/deployed_model.py
geti_sdk/deployment/predictions_postprocessing/results_converter/results_to_prediction_converter.py
geti_sdk/prediction_visualization/visualizer.py

Update the 'DeployedModel' class to handle the new 'Anomaly' task

Fix anomaly deployed models

---

geti_sdk/deployment/predictions_postprocessing/results_converter/results_to_prediction_converter.py

Filter out empty label ID in Model's configuration.
Develop PR: https://github.com/openvinotoolkit/geti-sdk/pull/534

CVS-159908 - Fix empty label ID in configuration [release-2.6]

---

CHANGELOG.md
geti_sdk/_version.py
geti_sdk/deployment/predictions_postprocessing/results_converter/results_to_prediction_converter.py
tests/pre-merge/unit/deployment/test_prediction_converter.py

[CVS-160148](https://jira.devtools.intel.com/browse/CVS-160148)
main branch PR: https://github.com/openvinotoolkit/geti-sdk/pull/539
- Added label sorting according to ModelAPI order for all converters when available.
- Added fallback to user legacy label names for classification results when label cannot be found

bugfix: classification not working with label that contain spaces

---

.github/dependabot.yml

This PR configure Dependabot for Actions

Enable Dependabot for Actions

---

geti_sdk/deployment/deployed_model.py

[CVS-160885](https://jira.devtools.intel.com/browse/CVS-160885)

CVS-160885 - Update tiling configuration for OTX 2

---

geti_sdk/deployment/deployed_model.py
requirements/requirements.txt

[CVS-158875](https://jira.devtools.intel.com/browse/CVS-158875)

CVS-158875 - Replace xml with defusedxml

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Add an issue template to report bugs.

add template for reporting bugs

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

add issue template for feature requests

add issue template for feature requests

---

.github/ISSUE_TEMPLATE/question.yaml

add issue template for questions

add issue template for questions

---

CHANGELOG.md
geti_sdk/_version.py

Update dev version to 2.10 and add changelog skeleton for coming release.
```python
#
#
#
```

update version and changelog

---

CHANGELOG.md
geti_sdk/_version.py
geti_sdk/deployment/deployed_model.py
geti_sdk/deployment/predictions_postprocessing/results_converter/results_to_prediction_converter.py

Backport of #613
```python
#
#
#
```

Bugfix: KP deployment crash after label renaming

---

CHANGELOG.md
geti_sdk/_version.py
geti_sdk/prediction_visualization/shape_drawer.py

Backport of #617 
```python
#
#
#
```

ITEP-71447 bugfix: keypoint predictions not displayed properly in demo code [release-2.10]

---

geti_sdk/data_models/media.py
tests/fixtures/unit_tests/media.py

Adds preprocessing information to media entities.
```python
#
#
#
```

ITEP-70349: Update geti-sdk to handle async media preprocessing
